/**
 * FC-008 Sprint 4A — parsing the frozen model artifacts into validated types.
 *
 * PURE. No filesystem, no crypto, no network, no Python. This module turns
 * `unknown` JSON into strongly typed artifacts or refuses, and nothing downstream
 * is allowed to see the `unknown` form.
 *
 * Reading bytes and verifying SHA-256 lives in `artifact-source.ts` in the
 * Node-only `@futureclick/futurebench-dataset` package, not here, because
 * everything under this package's `src/` is required to be free of Node builtins
 * — an invariant `tests/isolation.test.ts` enforces by scanning every file. The
 * split is what lets this parser run wherever the runtime runs.
 *
 * WHAT "VALIDATED" MEANS HERE
 *
 * The artifacts are generated by the frozen Python trainer, so the risk is not a
 * hostile file — it is a DRIFTED one: a regenerated artifact whose feature order
 * shifted, whose class order was re-sorted, or whose calibration belongs to the
 * other model family. Every one of those produces a numerically plausible result
 * that is silently wrong, which is why identity is checked against an independent
 * reference rather than against the artifact's own self-description:
 *
 * - Head orders are compared to `FC008_MATRIX_*` in `support-matrix.ts`, which is
 *   maintained in TypeScript and was never produced by the trainer. An artifact
 *   that re-sorted its verbs alphabetically fails here instead of quietly mapping
 *   logit 0 onto a different verb.
 * - Class order is compared to the frozen support matrix class numbering.
 * - Shapes are compared to the declared `shape` field AND to the frozen counts, so
 *   an artifact cannot declare a shape that matches its own wrong data.
 * - Every coefficient and intercept must be finite. A single NaN in a 13x370
 *   matrix would otherwise surface as a NaN probability much later, in a metric.
 *
 * Cross-family and cross-artifact checks live in `parseArtifactBundle`, because a
 * calibration artifact is only meaningful relative to the model it was fitted on.
 */

import { FC008_FEATURE_POLICY_VERSION } from "../feature-policy.js";
import { type Fc008ModelFamily, SHA256_HEX_REGEX } from "../hypothesis.js";
import {
  FC008_MATRIX_OBJECT_KIND_COUNT,
  FC008_MATRIX_OBJECT_KINDS,
  FC008_MATRIX_TRANSITION_PROPERTIES,
  FC008_MATRIX_TRANSITION_PROPERTY_COUNT,
  FC008_MATRIX_VERB_COUNT,
  FC008_MATRIX_VERBS,
  FC008_SUPPORT_MATRIX,
  FC008_SUPPORT_MATRIX_VERSION,
  FC008_SUPPORTED_TUPLE_COUNT,
} from "../support-matrix.js";

/** The frozen feature count. Not negotiable and not inferred from the file. */
export const FC008_FROZEN_FEATURE_COUNT = 370;

/** Artifact schema version this loader understands. */
export const FC008_ARTIFACT_SCHEMA_VERSION = "1.0";

/** Frozen class numbering, from the TypeScript support matrix. */
export const FC008_FROZEN_CLASS_ORDER: readonly number[] = Object.freeze(
  FC008_SUPPORT_MATRIX.map((entry) => entry.classNumber),
);

/**
 * Largest absolute coefficient accepted.
 *
 * Generous rather than tuned: the purpose is to catch a corrupt or exploded
 * artifact, not to express an opinion about regularization. The frozen models are
 * orders of magnitude below this.
 */
export const MAX_ABSOLUTE_COEFFICIENT = 1_000;

/** Why an artifact was refused. Categorical so a caller cannot widen it. */
export const ARTIFACT_LOAD_REFUSALS = Object.freeze([
  "not-an-object",
  "schema-version-unsupported",
  "model-family-unexpected",
  "field-missing",
  "field-type-invalid",
  "shape-mismatch",
  "feature-count-mismatch",
  "feature-order-mismatch",
  "class-order-mismatch",
  "head-order-mismatch",
  "head-missing",
  "non-finite-value",
  "coefficient-out-of-range",
  "identity-mismatch",
  "cross-family-artifact",
  "hash-mismatch",
  "temperature-invalid",
  "threshold-invalid",
] as const);
export type ArtifactLoadRefusal = (typeof ARTIFACT_LOAD_REFUSALS)[number];

/**
 * A refusal to load an artifact.
 *
 * Carries the categorical reason plus a bounded human path/detail. The reason is
 * what callers branch on; the detail exists so a drifted artifact is diagnosable
 * without reading the file by hand.
 */
export class ArtifactLoadError extends Error {
  readonly refusal: ArtifactLoadRefusal;
  readonly path: string;

  constructor(refusal: ArtifactLoadRefusal, path: string, detail: string) {
    super(`${refusal} at ${path}: ${detail}`);
    this.name = "ArtifactLoadError";
    this.refusal = refusal;
    this.path = path;
  }
}

function fail(refusal: ArtifactLoadRefusal, path: string, detail: string): never {
  throw new ArtifactLoadError(refusal, path, detail);
}

function asRecord(value: unknown, path: string): Record<string, unknown> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    fail("not-an-object", path, "expected a JSON object");
  }
  return value as Record<string, unknown>;
}

function readRequiredString(source: Record<string, unknown>, key: string, path: string): string {
  const value = source[key];
  if (typeof value !== "string" || value.length === 0) {
    fail("field-missing", `${path}.${key}`, "expected a non-empty string");
  }
  return value;
}

function readSha256(source: Record<string, unknown>, key: string, path: string): string {
  const value = readRequiredString(source, key, path);
  if (!SHA256_HEX_REGEX.test(value)) {
    fail("field-type-invalid", `${path}.${key}`, "expected 64 lowercase hex characters");
  }
  return value;
}

function readDenseArray(value: unknown, path: string): readonly unknown[] {
  if (!Array.isArray(value)) {
    fail("field-type-invalid", path, "expected an array");
  }
  // A hole in a JSON-parsed array cannot normally occur, but an artifact handed
  // to us from another in-process producer could carry one, and `undefined * x`
  // is NaN rather than an error.
  for (let index = 0; index < value.length; index += 1) {
    if (!Object.hasOwn(value, index)) {
      fail("field-type-invalid", `${path}[${index}]`, "array must be dense");
    }
  }
  return value;
}

function readFiniteVector(value: unknown, expected: number, path: string): readonly number[] {
  const raw = readDenseArray(value, path);
  if (raw.length !== expected) {
    fail("shape-mismatch", path, `expected exactly ${expected} values, received ${raw.length}`);
  }
  const out: number[] = [];
  for (let index = 0; index < raw.length; index += 1) {
    const entry = raw[index];
    if (typeof entry !== "number" || !Number.isFinite(entry)) {
      fail(
        "non-finite-value",
        `${path}[${index}]`,
        `expected a finite number, received ${String(entry)}`,
      );
    }
    if (Math.abs(entry) > MAX_ABSOLUTE_COEFFICIENT) {
      fail(
        "coefficient-out-of-range",
        `${path}[${index}]`,
        `magnitude ${Math.abs(entry)} exceeds ${MAX_ABSOLUTE_COEFFICIENT}`,
      );
    }
    out.push(entry);
  }
  return Object.freeze(out);
}

function readFiniteMatrix(
  value: unknown,
  rows: number,
  columns: number,
  path: string,
): readonly (readonly number[])[] {
  const raw = readDenseArray(value, path);
  if (raw.length !== rows) {
    fail("shape-mismatch", path, `expected exactly ${rows} rows, received ${raw.length}`);
  }
  const out: (readonly number[])[] = [];
  for (let index = 0; index < raw.length; index += 1) {
    out.push(readFiniteVector(raw[index], columns, `${path}[${index}]`));
  }
  return Object.freeze(out);
}

/** The declared `shape` field must agree with the frozen dimensions. */
function assertDeclaredShape(declared: unknown, expected: readonly number[], path: string): void {
  const raw = readDenseArray(declared, path);
  if (raw.length !== expected.length || raw.some((value, index) => value !== expected[index])) {
    fail(
      "shape-mismatch",
      path,
      `declared shape ${JSON.stringify(raw)} does not equal the frozen ${JSON.stringify(expected)}`,
    );
  }
}

function assertExactStringOrder(
  value: unknown,
  expected: readonly string[],
  refusal: ArtifactLoadRefusal,
  path: string,
): readonly string[] {
  const raw = readDenseArray(value, path);
  if (raw.length !== expected.length) {
    fail(refusal, path, `expected ${expected.length} entries, received ${raw.length}`);
  }
  for (let index = 0; index < expected.length; index += 1) {
    if (raw[index] !== expected[index]) {
      fail(
        refusal,
        `${path}[${index}]`,
        `expected ${JSON.stringify(expected[index])}, received ${JSON.stringify(raw[index])}`,
      );
    }
  }
  return Object.freeze(expected.slice());
}

function assertFrozenClassOrder(value: unknown, path: string): readonly number[] {
  const raw = readDenseArray(value, path);
  if (raw.length !== FC008_SUPPORTED_TUPLE_COUNT) {
    fail(
      "class-order-mismatch",
      path,
      `expected ${FC008_SUPPORTED_TUPLE_COUNT} class numbers, received ${raw.length}`,
    );
  }
  for (let index = 0; index < FC008_FROZEN_CLASS_ORDER.length; index += 1) {
    if (raw[index] !== FC008_FROZEN_CLASS_ORDER[index]) {
      fail(
        "class-order-mismatch",
        `${path}[${index}]`,
        `expected class ${FC008_FROZEN_CLASS_ORDER[index]}, received ${String(raw[index])}`,
      );
    }
  }
  return Object.freeze(FC008_FROZEN_CLASS_ORDER.slice());
}

/**
 * Identities every frozen artifact repeats.
 *
 * Parsed as a unit so the bundle check can compare them across the triplet
 * without each parser growing its own copy of the comparison.
 */
export interface ArtifactSharedIdentity {
  readonly datasetHash: string;
  readonly vocabularyHash: string;
  readonly supportMatrixVersion: string;
  readonly featurePolicyVersion: string;
}

function readSharedIdentity(source: Record<string, unknown>, path: string): ArtifactSharedIdentity {
  const supportMatrixVersion = readRequiredString(source, "supportMatrixVersion", path);
  const featurePolicyVersion = readRequiredString(source, "featurePolicyVersion", path);
  // Compared to the TypeScript constants, not merely to each other: an artifact
  // built under a different support matrix would otherwise be self-consistent.
  if (supportMatrixVersion !== FC008_SUPPORT_MATRIX_VERSION) {
    fail(
      "identity-mismatch",
      `${path}.supportMatrixVersion`,
      `expected ${FC008_SUPPORT_MATRIX_VERSION}, received ${supportMatrixVersion}`,
    );
  }
  if (featurePolicyVersion !== FC008_FEATURE_POLICY_VERSION) {
    fail(
      "identity-mismatch",
      `${path}.featurePolicyVersion`,
      `expected ${FC008_FEATURE_POLICY_VERSION}, received ${featurePolicyVersion}`,
    );
  }
  return Object.freeze({
    datasetHash: readSha256(source, "datasetHash", path),
    vocabularyHash: readSha256(source, "vocabularyHash", path),
    supportMatrixVersion,
    featurePolicyVersion,
  });
}

function assertSchemaAndFamily(
  source: Record<string, unknown>,
  expectedFamily: Fc008ModelFamily,
  path: string,
): void {
  const schemaVersion = readRequiredString(source, "schemaVersion", path);
  if (schemaVersion !== FC008_ARTIFACT_SCHEMA_VERSION) {
    fail(
      "schema-version-unsupported",
      `${path}.schemaVersion`,
      `expected ${FC008_ARTIFACT_SCHEMA_VERSION}, received ${schemaVersion}`,
    );
  }
  const modelFamily = readRequiredString(source, "modelFamily", path);
  if (modelFamily !== expectedFamily) {
    fail(
      "model-family-unexpected",
      `${path}.modelFamily`,
      `expected ${expectedFamily}, received ${modelFamily}`,
    );
  }
}

// ============================================================================
// MODEL ARTIFACTS
// ============================================================================

export interface JointModelArtifact {
  readonly modelFamily: "joint-logistic";
  readonly modelVersion: string;
  readonly schemaVersion: string;
  readonly identity: ArtifactSharedIdentity;
  /** Frozen class numbering, 1..13. */
  readonly classOrder: readonly number[];
  /** The frozen 370-feature order, exactly as fitted. */
  readonly featureOrder: readonly string[];
  /** 13 x 370. Row `k` is the weight vector for `classOrder[k]`. */
  readonly coefficients: readonly (readonly number[])[];
  /** 13 intercepts, aligned to `classOrder`. */
  readonly intercepts: readonly number[];
}

export interface FactorizedHead {
  readonly name: "verb" | "objectKind" | "transitionProperty";
  readonly classOrder: readonly string[];
  readonly coefficients: readonly (readonly number[])[];
  readonly intercepts: readonly number[];
}

/** Which head index each supported tuple draws from. */
export interface ClassHeadIndices {
  readonly classNumber: number;
  readonly verbIndex: number;
  readonly objectIndex: number;
  readonly transitionPropertyIndex: number;
}

export interface FactorizedModelArtifact {
  readonly modelFamily: "factorized-logistic";
  readonly modelVersion: string;
  readonly schemaVersion: string;
  readonly identity: ArtifactSharedIdentity;
  readonly classOrder: readonly number[];
  readonly featureOrder: readonly string[];
  readonly verb: FactorizedHead;
  readonly objectKind: FactorizedHead;
  readonly transitionProperty: FactorizedHead;
  /** Composition mapping, aligned to `classOrder`. */
  readonly classHeadIndices: readonly ClassHeadIndices[];
  readonly compositionVersion: string;
}

export type ModelArtifact = JointModelArtifact | FactorizedModelArtifact;

function readFeatureOrder(source: Record<string, unknown>, path: string): readonly string[] {
  const raw = readDenseArray(source.featureOrder, `${path}.featureOrder`);
  if (raw.length !== FC008_FROZEN_FEATURE_COUNT) {
    fail(
      "feature-count-mismatch",
      `${path}.featureOrder`,
      `expected ${FC008_FROZEN_FEATURE_COUNT} features, received ${raw.length}`,
    );
  }
  const seen = new Set<string>();
  const out: string[] = [];
  for (let index = 0; index < raw.length; index += 1) {
    const name = raw[index];
    if (typeof name !== "string" || name.length === 0) {
      fail("field-type-invalid", `${path}.featureOrder[${index}]`, "expected a non-empty string");
    }
    // A duplicate name would make the order ambiguous: two different indices
    // would claim the same feature, and a caller mapping by name would pick one
    // arbitrarily.
    if (seen.has(name)) {
      fail("feature-order-mismatch", `${path}.featureOrder[${index}]`, `duplicate feature ${name}`);
    }
    seen.add(name);
    out.push(name);
  }
  return Object.freeze(out);
}

export function parseJointModelArtifact(input: unknown, path = "jointModel"): JointModelArtifact {
  const source = asRecord(input, path);
  assertSchemaAndFamily(source, "joint-logistic", path);

  const shape = asRecord(source.shape, `${path}.shape`);
  assertDeclaredShape(
    shape.coefficients,
    [FC008_SUPPORTED_TUPLE_COUNT, FC008_FROZEN_FEATURE_COUNT],
    `${path}.shape.coefficients`,
  );
  assertDeclaredShape(shape.intercepts, [FC008_SUPPORTED_TUPLE_COUNT], `${path}.shape.intercepts`);

  return Object.freeze({
    modelFamily: "joint-logistic" as const,
    modelVersion: readRequiredString(source, "modelVersion", path),
    schemaVersion: FC008_ARTIFACT_SCHEMA_VERSION,
    identity: readSharedIdentity(source, path),
    classOrder: assertFrozenClassOrder(source.classOrder, `${path}.classOrder`),
    featureOrder: readFeatureOrder(source, path),
    coefficients: readFiniteMatrix(
      source.coefficients,
      FC008_SUPPORTED_TUPLE_COUNT,
      FC008_FROZEN_FEATURE_COUNT,
      `${path}.coefficients`,
    ),
    intercepts: readFiniteVector(
      source.intercepts,
      FC008_SUPPORTED_TUPLE_COUNT,
      `${path}.intercepts`,
    ),
  });
}

const HEAD_SPECIFICATIONS = Object.freeze([
  { name: "verb" as const, order: FC008_MATRIX_VERBS, count: FC008_MATRIX_VERB_COUNT },
  {
    name: "objectKind" as const,
    order: FC008_MATRIX_OBJECT_KINDS,
    count: FC008_MATRIX_OBJECT_KIND_COUNT,
  },
  {
    name: "transitionProperty" as const,
    order: FC008_MATRIX_TRANSITION_PROPERTIES,
    count: FC008_MATRIX_TRANSITION_PROPERTY_COUNT,
  },
]);

function parseHead(
  heads: Record<string, unknown>,
  specification: (typeof HEAD_SPECIFICATIONS)[number],
  path: string,
): FactorizedHead {
  const { name, order, count } = specification;
  if (!Object.hasOwn(heads, name)) {
    fail("head-missing", `${path}.${name}`, "frozen head is absent");
  }
  const head = asRecord(heads[name], `${path}.${name}`);
  // A head declares one flat coefficient shape, unlike the joint artifact which
  // declares coefficients and intercepts separately.
  assertDeclaredShape(head.shape, [count, FC008_FROZEN_FEATURE_COUNT], `${path}.${name}.shape`);

  return Object.freeze({
    name,
    classOrder: assertExactStringOrder(
      head.classOrder,
      order as readonly string[],
      "head-order-mismatch",
      `${path}.${name}.classOrder`,
    ),
    coefficients: readFiniteMatrix(
      head.coefficients,
      count,
      FC008_FROZEN_FEATURE_COUNT,
      `${path}.${name}.coefficients`,
    ),
    intercepts: readFiniteVector(head.intercepts, count, `${path}.${name}.intercepts`),
  });
}

function parseClassHeadIndices(input: unknown, path: string): readonly ClassHeadIndices[] {
  const raw = readDenseArray(input, path);
  if (raw.length !== FC008_SUPPORTED_TUPLE_COUNT) {
    fail(
      "shape-mismatch",
      path,
      `expected ${FC008_SUPPORTED_TUPLE_COUNT} entries, received ${raw.length}`,
    );
  }
  const out: ClassHeadIndices[] = [];
  for (let index = 0; index < raw.length; index += 1) {
    const entry = asRecord(raw[index], `${path}[${index}]`);
    const readIndex = (key: string, bound: number): number => {
      const value = entry[key];
      if (typeof value !== "number" || !Number.isInteger(value) || value < 0 || value >= bound) {
        fail(
          "field-type-invalid",
          `${path}[${index}].${key}`,
          `expected an integer in [0, ${bound}), received ${String(value)}`,
        );
      }
      return value;
    };
    const classNumber = entry.classNumber;
    // Composition is positional: entry `i` must describe `classOrder[i]`, or the
    // composed logit vector would be a permutation of the intended one.
    if (classNumber !== FC008_FROZEN_CLASS_ORDER[index]) {
      fail(
        "class-order-mismatch",
        `${path}[${index}].classNumber`,
        `expected ${FC008_FROZEN_CLASS_ORDER[index]}, received ${String(classNumber)}`,
      );
    }
    out.push(
      Object.freeze({
        classNumber: FC008_FROZEN_CLASS_ORDER[index] as number,
        verbIndex: readIndex("verbIndex", FC008_MATRIX_VERB_COUNT),
        objectIndex: readIndex("objectIndex", FC008_MATRIX_OBJECT_KIND_COUNT),
        transitionPropertyIndex: readIndex(
          "transitionPropertyIndex",
          FC008_MATRIX_TRANSITION_PROPERTY_COUNT,
        ),
      }),
    );
  }
  return Object.freeze(out);
}

export function parseFactorizedModelArtifact(
  input: unknown,
  path = "factorizedModel",
): FactorizedModelArtifact {
  const source = asRecord(input, path);
  assertSchemaAndFamily(source, "factorized-logistic", path);

  const heads = asRecord(source.heads, `${path}.heads`);
  const composition = asRecord(source.composition, `${path}.composition`);
  if (composition.learnedCombiner !== false) {
    fail(
      "identity-mismatch",
      `${path}.composition.learnedCombiner`,
      "frozen composition is additive with no learned combiner",
    );
  }

  const [verbSpec, objectSpec, propertySpec] = HEAD_SPECIFICATIONS;
  return Object.freeze({
    modelFamily: "factorized-logistic" as const,
    modelVersion: readRequiredString(source, "modelVersion", path),
    schemaVersion: FC008_ARTIFACT_SCHEMA_VERSION,
    identity: readSharedIdentity(source, path),
    classOrder: assertFrozenClassOrder(source.classOrder, `${path}.classOrder`),
    featureOrder: readFeatureOrder(source, path),
    verb: parseHead(heads, verbSpec as (typeof HEAD_SPECIFICATIONS)[number], `${path}.heads`),
    objectKind: parseHead(
      heads,
      objectSpec as (typeof HEAD_SPECIFICATIONS)[number],
      `${path}.heads`,
    ),
    transitionProperty: parseHead(
      heads,
      propertySpec as (typeof HEAD_SPECIFICATIONS)[number],
      `${path}.heads`,
    ),
    classHeadIndices: parseClassHeadIndices(
      composition.classOrderHeadIndices,
      `${path}.composition.classOrderHeadIndices`,
    ),
    compositionVersion: readRequiredString(
      composition,
      "compositionVersion",
      `${path}.composition`,
    ),
  });
}

// ============================================================================
// CALIBRATION AND POLICY
// ============================================================================

export interface CalibrationArtifact {
  readonly modelFamily: Fc008ModelFamily;
  readonly modelVersion: string;
  readonly calibrationArtifactVersion: string;
  readonly identity: ArtifactSharedIdentity;
  /** SHA-256 of the model artifact this temperature was fitted against. */
  readonly modelArtifactSha256: string;
  /** Frozen temperature. Strictly positive. */
  readonly temperature: number;
}

export function parseCalibrationArtifact(
  input: unknown,
  expectedFamily: Fc008ModelFamily,
  path = "calibration",
): CalibrationArtifact {
  const source = asRecord(input, path);
  assertSchemaAndFamily(source, expectedFamily, path);
  const fit = asRecord(source.temperatureFit, `${path}.temperatureFit`);
  const temperature = fit.temperature;
  if (typeof temperature !== "number" || !Number.isFinite(temperature) || temperature <= 0) {
    fail(
      "temperature-invalid",
      `${path}.temperatureFit.temperature`,
      `expected a finite positive number, received ${String(temperature)}`,
    );
  }
  return Object.freeze({
    modelFamily: expectedFamily,
    modelVersion: readRequiredString(source, "modelVersion", path),
    calibrationArtifactVersion: readRequiredString(source, "calibrationArtifactVersion", path),
    identity: readSharedIdentity(source, path),
    modelArtifactSha256: readSha256(source, "modelArtifactSha256", path),
    temperature,
  });
}

export interface PolicyArtifact {
  readonly modelFamily: Fc008ModelFamily;
  readonly modelVersion: string;
  readonly abstentionPolicyVersion: string;
  readonly calibrationArtifactVersion: string;
  readonly identity: ArtifactSharedIdentity;
  readonly modelArtifactSha256: string;
  readonly calibrationArtifactSha256: string;
  /** Frozen acceptance threshold on calibrated confidence, within [0, 1]. */
  readonly selectedConfidenceThreshold: number;
  /** Whether threshold selection fell back. Reported, never acted on here. */
  readonly fallbackUsed: boolean;
}

export function parsePolicyArtifact(
  input: unknown,
  expectedFamily: Fc008ModelFamily,
  path = "policy",
): PolicyArtifact {
  const source = asRecord(input, path);
  assertSchemaAndFamily(source, expectedFamily, path);
  const threshold = source.selectedConfidenceThreshold;
  if (
    typeof threshold !== "number" ||
    !Number.isFinite(threshold) ||
    threshold < 0 ||
    threshold > 1
  ) {
    fail(
      "threshold-invalid",
      `${path}.selectedConfidenceThreshold`,
      `expected a finite number within [0, 1], received ${String(threshold)}`,
    );
  }
  const fallbackUsed = source.fallbackUsed;
  if (typeof fallbackUsed !== "boolean") {
    fail("field-type-invalid", `${path}.fallbackUsed`, "expected a boolean");
  }
  return Object.freeze({
    modelFamily: expectedFamily,
    modelVersion: readRequiredString(source, "modelVersion", path),
    abstentionPolicyVersion: readRequiredString(source, "abstentionPolicyVersion", path),
    calibrationArtifactVersion: readRequiredString(source, "calibrationArtifactVersion", path),
    identity: readSharedIdentity(source, path),
    modelArtifactSha256: readSha256(source, "modelArtifactSha256", path),
    calibrationArtifactSha256: readSha256(source, "calibrationArtifactSha256", path),
    selectedConfidenceThreshold: threshold,
    fallbackUsed,
  });
}

// ============================================================================
// BUNDLE: THE TRIPLET, CHECKED AS A UNIT
// ============================================================================

/**
 * One family's validated model, calibration, and policy, proven to belong together.
 *
 * The hashes are supplied by the caller that read the bytes, because this module
 * does no hashing. They are then checked against the cross-references inside the
 * artifact bodies, which is what makes a cross-family or re-fitted calibration
 * impossible to pair with the wrong model.
 */
export interface ArtifactBundle<TModel extends ModelArtifact = ModelArtifact> {
  readonly modelFamily: Fc008ModelFamily;
  readonly model: TModel;
  readonly calibration: CalibrationArtifact;
  readonly policy: PolicyArtifact;
  readonly modelSha256: string;
  readonly calibrationSha256: string;
  readonly policySha256: string;
}

export interface ArtifactBundleInput {
  readonly modelFamily: Fc008ModelFamily;
  readonly model: unknown;
  readonly calibration: unknown;
  readonly policy: unknown;
  readonly modelSha256: string;
  readonly calibrationSha256: string;
  readonly policySha256: string;
}

export function parseArtifactBundle(input: ArtifactBundleInput): ArtifactBundle {
  const { modelFamily } = input;
  const model =
    modelFamily === "joint-logistic"
      ? parseJointModelArtifact(input.model, `${modelFamily}.model`)
      : parseFactorizedModelArtifact(input.model, `${modelFamily}.model`);
  const calibration = parseCalibrationArtifact(
    input.calibration,
    modelFamily,
    `${modelFamily}.calibration`,
  );
  const policy = parsePolicyArtifact(input.policy, modelFamily, `${modelFamily}.policy`);

  // Content-linked, not filename-linked. The calibration must name the exact
  // model bytes it was fitted on, and the policy must name both. This is what
  // rejects a factorized calibration handed in beside a joint model even when
  // every file is individually valid.
  if (calibration.modelArtifactSha256 !== input.modelSha256) {
    fail(
      "cross-family-artifact",
      `${modelFamily}.calibration.modelArtifactSha256`,
      `references model ${calibration.modelArtifactSha256}, but the supplied model hashes to ${input.modelSha256}`,
    );
  }
  if (policy.modelArtifactSha256 !== input.modelSha256) {
    fail(
      "cross-family-artifact",
      `${modelFamily}.policy.modelArtifactSha256`,
      `references model ${policy.modelArtifactSha256}, but the supplied model hashes to ${input.modelSha256}`,
    );
  }
  if (policy.calibrationArtifactSha256 !== input.calibrationSha256) {
    fail(
      "cross-family-artifact",
      `${modelFamily}.policy.calibrationArtifactSha256`,
      `references calibration ${policy.calibrationArtifactSha256}, but the supplied calibration hashes to ${input.calibrationSha256}`,
    );
  }

  // Versions must agree where two artifacts both carry the same one.
  if (calibration.modelVersion !== model.modelVersion) {
    fail(
      "identity-mismatch",
      `${modelFamily}.calibration.modelVersion`,
      `expected ${model.modelVersion}, received ${calibration.modelVersion}`,
    );
  }
  if (policy.modelVersion !== model.modelVersion) {
    fail(
      "identity-mismatch",
      `${modelFamily}.policy.modelVersion`,
      `expected ${model.modelVersion}, received ${policy.modelVersion}`,
    );
  }
  if (policy.calibrationArtifactVersion !== calibration.calibrationArtifactVersion) {
    fail(
      "identity-mismatch",
      `${modelFamily}.policy.calibrationArtifactVersion`,
      `expected ${calibration.calibrationArtifactVersion}, received ${policy.calibrationArtifactVersion}`,
    );
  }

  for (const key of [
    "datasetHash",
    "vocabularyHash",
    "supportMatrixVersion",
    "featurePolicyVersion",
  ] as const) {
    for (const [label, other] of [
      ["calibration", calibration.identity],
      ["policy", policy.identity],
    ] as const) {
      if (other[key] !== model.identity[key]) {
        fail(
          "identity-mismatch",
          `${modelFamily}.${label}.${key}`,
          `expected ${model.identity[key]}, received ${other[key]}`,
        );
      }
    }
  }

  return Object.freeze({
    modelFamily,
    model,
    calibration,
    policy,
    modelSha256: input.modelSha256,
    calibrationSha256: input.calibrationSha256,
    policySha256: input.policySha256,
  });
}

/**
 * Require the two families to share one feature order, byte for byte.
 *
 * RQ1 compares the families "trained on the same observations and privacy-safe
 * features". If their feature orders diverged, every comparison downstream would
 * be between models reading different inputs, and the frozen preregistration's
 * `sharedAcrossFamilies: true` claim would be false. Checked rather than assumed.
 */
export function assertSharedFeatureOrder(
  joint: JointModelArtifact,
  factorized: FactorizedModelArtifact,
): void {
  if (joint.featureOrder.length !== factorized.featureOrder.length) {
    fail(
      "feature-count-mismatch",
      "featureOrder",
      `joint has ${joint.featureOrder.length} features, factorized has ${factorized.featureOrder.length}`,
    );
  }
  for (let index = 0; index < joint.featureOrder.length; index += 1) {
    if (joint.featureOrder[index] !== factorized.featureOrder[index]) {
      fail(
        "feature-order-mismatch",
        `featureOrder[${index}]`,
        `joint has ${JSON.stringify(joint.featureOrder[index])}, factorized has ${JSON.stringify(factorized.featureOrder[index])}`,
      );
    }
  }
}
